name: aicycle_buyme_plus
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.1
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/front/
    - assets/images/rear/
    - assets/images/left/
    - assets/images/right/
    - assets/images/front_left/
    - assets/images/front_right/
    - assets/images/rear_left/
    - assets/images/rear_right/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
