name: aicycle_buyme_lib
description: A new Flutter package project.
version: 0.0.1
homepage: https://aicycle.ai/

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.10.5+5
  flutter:
    sdk: flutter
  get: ^4.6.6
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
